### ISSUE TITLE
Chinese i10n

### ISSUE THREAD

**Issue by DYColdWind** [DoctorFTB/ThaumicGrid#1]
block.thaumicgrid:thaumic_grid.name=奥术合成终端
gui.thaumicgrid:thaumic_grid=奥术合成终端

**Comment by DoctorFTB** [comment]
What is file name need for this lang?

**Comment by DoctorFTB** [comment]
@DYColdWind ^

**Comment by DYColdWind** [comment]
> What is file name need for this lang?

zh_cn.lang

**Comment by DoctorFTB** [comment]
I update lang.
Available after 1.0.6 versions.
