### ISSUE TITLE
Some recipes recipes are not properly moved into the Grid

### ISSUE THREAD

**Issue by angelnc1989** [DoctorFTB/ThaumicGrid#10]
https://gfycat.com/PleasedWearyJapanesebeetle
The recipe is not properly moved by clicking the "Move Items" button. There are some other recipes with this bug. All items are of course present in the Refined Storage system.

**Comment by DoctorFTB** [comment]
I fix 2x2 recipes.. I break 3x3 recipes..
After I have empty time - I fix it.

**Comment by DoctorFTB** [comment]
Hm.. Recipe Thaumometer normally work.
From what mod recipe on gif?

**Comment by angelnc1989** [comment]
Thaumic Additions Reconstructed

**Comment by DoctorFTB** [comment]
Try 1.0.7 version.

**Comment by angelnc1989** [comment]
Seems to be fixed.
