### ISSUE TITLE
Crash with External Storage

### ISSUE THREAD

**Issue by angelnc1989** [DoctorFTB/ThaumicGrid#11]
The first crash happened when shiftclicking a recipe into the crafting area.
The second happened when taking one of the ingredients of the same recipe out of the Thaumic Grid.

https://pastebin.com/iNAw56B4
https://pastebin.com/ssyKLCAG

**Comment by DoctorFTB** [comment]
RC version?

**Comment by DoctorFTB** [comment]
Try 1.0.8 version.

**Comment by angelnc1989** [comment]
Seems to be fixed 👍
