### ISSUE TITLE
[1.0.8] Crashes client on startup

### ISSUE THREAD

**Issue by kreezxil** [DoctorFTB/ThaumicGrid#12]
In my World of Dragons mod pack of which I am the author. One of the many players that use my pack has reported that Thaumic Grid is crashing their client. **This is the only** report I've gotten like this. I have instructed the player to do quite a bit of uninstalling, system cleaning, and driver updating to no avail.

Their Crash Report: https://pastebin.com/Zg7ADdUu

Their Latest Log: https://pastebin.com/9SmeLvev

The thread on CurseForge where I am managing the issue if you would like to take part in it: https://minecraft.curseforge.com/projects/world-of-dragons/issues/42

**Comment by DoctorFTB** [comment]
Try 1.0.9 version.

**Comment by kreezxil** [comment]
Since for me 1.0.8 actually works, did you find an actual null pointer call there. I'm updating my pack and I've asked the player in question to test it. However, my pack will likely update before they report it and if it works they probably won't report that it did but it would nice if they would.

**Comment by kreezxil** [comment]
As I suspected, they won't be testing it. I'll force the test tho with an update later today.

```
I went in today to load up the game, and it seems to be working fine!?

I haven't changed anything, added any files or updates or anything since I first sent you the report a few days ago. I've played other modpacks in-between, but that shouldn't have any bearing on whether your modpack loads or not

I'll keep an eye on it, and if I get the error again I'll try updating Thaumic Grid manually and see if that helps.

When I had mentioned my problems to others on the server, two mentioned that they had crashed when first loading the pack, but it had never happened again.

I'm sorry if I wasted your time with this, but thanks for taking the time out to look at my problem and trying to solve it.  
```

**Comment by DoctorFTB** [comment]
I think this crash if player not have stable/any Ethernet connection.

**Comment by kreezxil** [comment]
Which is weird because they showed it happening at the same place multiple
times.

**Comment by DoctorFTB** [comment]
@kreezxil If problem solved - close issue.

**Comment by kreezxil** [comment]
I don't know if it's resolved. They certainly aren't telling me anything.
