### ISSUE TITLE
[Enhancement] Config option to turn off update check

### ISSUE THREAD

**Issue by ghost** [DoctorFTB/ThaumicGrid#13]
Why?

Maintainers of public mod packs often want to disable update messages. Players will pester the maintainer to update when there is often a very good reason not to. The maintainer will actively check for the updates and push them to the player. This prevents a lot of nuisance issue reports and makes for a better player experience. (Some people will get uncomfortable knowing there's a higher version number available that they don't have even if it isn't the best version for them!) 

Why wouldn't we have every mod up to its latest release? Dependencies. Many times you just can't. Perhaps one of the other mods in the pack is stuck on an older version of Forge or some other mod which creates a dependency chain. For example, maybe I need to run an older Thaumcraft or an older Refined Storage for any number of reasons. 

... or, in this case, Thaumic Grid is saying there is an update even though 1.0.9 is installed and 1.0.9 is the latest available file on curseforge.

**Comment by DoctorFTB** [comment]
Try 1.0.10 version.

**Comment by DoctorFTB** [comment]
@EnmaPlays If problem solved - close issue.
