### ISSUE TITLE
1.0.10 Crystal error

### ISSUE THREAD

**Issue by Jkosio23** [DoctorFTB/ThaumicGrid#15]
The faint image of the crystals swaps the slots for terra and ignis

**Comment by DoctorFTB** [comment]
For terra slot show ignis texture.
For ignis slot show terra texture.
Right?

**Comment by Jkosio23** [comment]
Right.

**Comment by Jkosio23** [comment]
if you could make a version of the mod that is compatible with more than one version of Refined Storage, that would be great.

**Comment by DoctorFTB** [comment]
Textures fixed in dev.
About one version with with all versions RS - its not really.
Author RS add/change elemets & this elemetns need change me.
