### ISSUE TITLE
[Idea] Thaumic Storage Cards

### ISSUE THREAD

**Issue by DisKorrupt** [DoctorFTB/ThaumicGrid#18]
using 3 warded jars in place of the glass of the 1K Storage Disk would make a 1K Warded Storage DisK, which can store any combination of essentia, up to 1000 points, rather than having a bunch of warded jars with like 5 essentia, you have 85/1000 bytes used for your less commonly used jars, this would also enable the ability to make blueprints requiring essentia as a crafting component, in a Thaumic pattern grid, there would be an additional bar or 2 to place essentia crystals for whatever type of essentia you need and dictate how much essentia is necessary, you can also put in the processing mode an item to put into a machine to say what item to put in a machine like the distiller and tell it how much essentia will come out, when requesting essentia, it will use the item that will produce the most essentia that it's been told about of that type, it can also be plugged into the essentia distillery with crystals to represent essentia and the 2 output essentia types (also represented by the blueprint in the form of crystals),

**Comment by DoctorFTB** [comment]
About add Essetia storage in disks - you can use Thaumic Energistics, but its only for AE.
I not planned release storage in disks for RS.
