### ISSUE TITLE
Crash when placing the last ingredient of a recipe in the Grid

### ISSUE THREAD

**Issue by angelnc1989** [DoctorFTB/ThaumicGrid#3]
https://pastebin.com/RnD7kETm

The game crashes the moment I place the last ingredient for a recipe in the Grid.
This happens since I updated Thaumcraft to 6.1 beta 23.

**Comment by DoctorFTB** [comment]
In progress..

**Comment by DoctorFTB** [comment]
Try 1.0.3 version.

**Comment by angelnc1989** [comment]
It requires Refined Storage 1.6.4 and the latest version on Curseforge is 1.6.3.

**Comment by DoctorFTB** [comment]
Ohh.. Modders..
Check 1.0.4.

**Comment by DoctorFTB** [comment]
If work - U can close Issue.
