### ISSUE TITLE
JEI Hotkeys don't work on items in the Thaumic Grid

### ISSUE THREAD

**Issue by angelnc1989** [DoctorFTB/ThaumicGrid#4]
Pressing JEI Hotkeys to display uses or recipes for an item don't work in the Thaumic Grid.
They work in Refined Storage Grids and on items in the 3x3 crafting grid.

**Comment by DoctorFTB** [comment]
ThaumCraft not have normally JEI support.
In this moment I work on add integration with Thaumic JEI.

**Comment by angelnc1989** [comment]
It's not only about Thaumic JEI. If I press U on an item it should show me all uses for that item. If I press R it should show me all recipes. This is regardless of Thaumic JEI. In a normal Refined Storage Grid it works fine and in a Thaumic Grid it doesn't work at all.

**Comment by DoctorFTB** [comment]
For me: if I press U - I show item uses, if I press R - I show item recipe.
Normally.

**Comment by angelnc1989** [comment]
No idea why, but it doesn't work for me.

**Comment by DoctorFTB** [comment]
Mod list & proof.
https://gyazo.com/6eb45dce99e49d655e6b2b1578078813

**Comment by angelnc1989** [comment]
You were misunderstanding me.
![unbenannt](https://user-images.githubusercontent.com/5382585/44785109-0f971500-ab90-11e8-9df2-f5dc3fcfa744.JPG)
Green area works, red doesn't.

**Comment by DoctorFTB** [comment]
Oh..
Ok, this fixed on dev version.
After I add Thaumic JEI integration - I upload to curse.
Try 1.0.6 version after upload to curse.

**Comment by angelnc1989** [comment]
Sure =)

**Comment by DoctorFTB** [comment]
1.0.6 version is uploaded.

**Comment by angelnc1989** [comment]
Everything works now. The Thaumic JEI compatibility is amazing. It should probably be a part of Thaumic JEI and not Thaumic Grid, so it works for people who don't want Refined Storage in their modpack.
How do you feel about making a pull request on their project?

**Comment by DoctorFTB** [comment]
Thaumic JEI work only with ThaumCraft.
I not understand about what you say.
What I need add Thaumic JEI with pull request?

**Comment by angelnc1989** [comment]
Didn't you add the "Move Items" Button which you can shift-click to move items into the crafting grid?
As far as I know that is not a thing when you only have Thaumcraft and Thaumic JEI.

**Comment by DoctorFTB** [comment]
Button "Move Items" have on Arcane Workbench from ThaumCraft.
Button on Thuamic Grid added by me.

**Comment by angelnc1989** [comment]
Oh, you're right. The strange thing is, I never had the button until your recent update, even in the Thaumcraft Arcane Workbench. Maybe a bug in Thaumic JEI. I don't know. As long as it works now.
