### ISSUE TITLE
Workbench Charger compatibility

### ISSUE THREAD

**Issue by angelnc1989** [DoctorFTB/ThaumicGrid#8]
Some recipes in Thaumcraft require a lot of vis. More than one chunk usually holds. On the Arcane Workbench a Workbench Charger helps with that. It would be nice to have a way to incorporate a Workbench Charger into the Thaumic Grid to be able to craft all recipes.
One way would be to make it placable on the Thaumic Grid although that would probably look weird.
Another way would be a new block which is an advanced version of the Thaumic Grid and call pull vis from all surrounding chunks.

**Comment by DoctorFTB** [comment]
Temporary variant with charger integration check in "Images" on project.

**Comment by angelnc1989** [comment]
Works great so far =)
Probably not a good long term solution, but a nice workaround.
Not sure if I should close the issue or if you want to keep it open. Do that yourself.

**Comment by DoctorFTB** [comment]
After I have empty time - I create specific slot wich add integration with Workbench Charger.
