### ISSUE TITLE
Exporter into Grid

### ISSUE THREAD

**Issue by TheFacelessOne** [DoctorFTB/ThaumicGrid#9]
Hi, is there any way to get similar functionality for the grid as the pattern grid? if you export patterns into a pattern grid it fills the pattern slot.

Could we get something similar to this for the vis crystals? so attaching an exporter to the grid will fill the vis crystal slot

**Comment by TheFacelessOne** [comment]
*apologies* I opened this and then looked at the previous issues. I decided to change it to a different suggestion I had

**Comment by DoctorFTB** [comment]
Hi.
U about autocrafting, right?

**Comment by TheFacelessOne** [comment]
No, I just mean in the regular crafting grid. I will log into minecraft, take a video and give an example of what I mean now.

**Comment by TheFacelessOne** [comment]
An example of how the pattern grid works 

https://youtu.be/SWFCiF8E3mI

**Comment by DoctorFTB** [comment]
You not need this system.
After craft required amount put in slots automatic.
Proof: 
https://gyazo.com/aa3e3376b5f4ff3410fa149d5375d265

**Comment by TheFacelessOne** [comment]
Ah, I did not realise. Thank you for the swift reply.
